# Generated by Django 4.0 on 2022-01-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hairdresser', models.TextField()),
                ('Client', models.TextField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
