# Generated by Django 4.0 on 2022-01-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_barber_remove_offer_client_remove_offer_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Time',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
